layout_spectrum: 0.9699248
name: TonyEllisMedia
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.6424958
  lightness: 0.6686341
  saturation: 0.4013491
  rhythmicContrast: 0.2816189
  brandColors:
    - '#BCA388'
    - '#3A281E'
    - '#E0D9CE'
    - '#775D4B'
    - '#BD0E14'
typography_spectrum: 0.5564924
