layout_spectrum: 0.9699248
name: TonyEllisMedia
typography_spectrum: 0.5564924
color:
  brandStrength: 0.6424958
  saturation: 0.6997006
  brandColors:
    - '#BCA388'
    - '#3A281E'
    - '#E0D9CE'
    - '#775D4B'
    - '#BD0E14'
  lightness: 0.7155187
  rhythmicContrast: 0.1883451
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
