layout_spectrum: 0.9699248
typography_spectrum: 0.5564924
color:
  lightness: 0.7155187
  brandStrength: 0.6424958
  saturation: 0.6997006
  rhythmicContrast: 0.1883451
  brandColors:
    - '#BCA388'
    - '#3A281E'
    - '#E0D9CE'
    - '#775D4B'
    - '#BD0E14'
name: TonyEllisMedia
